version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - cd backend && npm install

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo Build started on `date`
      - echo Testing backend...
      - cd backend && npm test --passWithNoTests

  build:
    commands:
      - echo Build phase started on `date`
      - echo Copying frontend files...
      - cd ..
      - echo Frontend files ready for deployment

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deploying to S3...
      - aws s3 sync frontend/ s3://$WEBSITE_BUCKET --delete
      - echo Creating CloudFront invalidation...
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
      - echo Deployment completed successfully!

artifacts:
  files:
    - "**/*"
  name: portfolio-build-$(date +%Y-%m-%d-%H-%M-%S)

cache:
  paths:
    - backend/node_modules/**/*
